/-
Machine-checks the audit surface from both sides.

`#modelClosure` and `#modelClosureOfType` say nothing in a definition or a
statement escapes `Nfa/Model/`. `#surplusIn` says nothing sits in a
module that its own claims do not reach. Either alone lets the surface drift:
the first two never shrink it, and the third never stops it leaking.

This is tooling, hence proof content, hence deliberately *outside* the surface
it checks.

Seeding from a theorem's **type** rather than its value is the crux: the proof
may use anything, and routinely should. Only the statement is constrained.
-/
import Lean

open Lean Elab Command

namespace Nfa.Meta

/-- All `Nfa` constants reachable from a seed, through both types and values. -/
private partial def closureAux (env : Environment) :
    NameSet → List Name → NameSet → NameSet
  | _, [], acc => acc
  | seen, c :: rest, acc =>
    if seen.contains c then closureAux env seen rest acc
    else
      let seen := seen.insert c
      let acc := if (`Nfa).isPrefixOf c then acc.insert c else acc
      match env.find? c with
      | none => closureAux env seen rest acc
      | some ci =>
        let next := ci.type.getUsedConstants.toList
          ++ (match ci.value? with | some v => v.getUsedConstants.toList | none => [])
        closureAux env seen (next ++ rest) acc

/-- Which module defines a constant.

    `getModuleIdxFor?` is the only route in current Lean: `getModuleFor?` was
    removed, and an index has to be looked up in the header's module table. A
    constant with no index is not imported at all — it belongs to the module
    being elaborated right now. -/
private def moduleOf (env : Environment) (c : Name) : Name :=
  match env.getModuleIdxFor? c with
  | some idx => (env.allImportedModuleNames[idx.toNat]?).getD `«unknown»
  | none => env.mainModule

/-- **Modules a statement may unfold into besides `Model/`.**

`Arlib.Computation` supplies the currency a cost is counted in — `StdOp`,
`Cell` — so a running-time or space statement necessarily mentions it. A
development that states no resource bound never reaches it and can leave this
list alone.

Admitting it is a real widening: an `Arlib.Computation` constant in a headline
statement is trusted without being read here. What backs it is that arlib is a
library with its own seal and its own audit, rather than this development's
proof scratch, and that the alternative is a translation table a reader has to
check by eye for no gain.

It is deliberately not `Arlib`: only the computation area, and only because a
cost claim has to name the unit it is in. -/
private def admittedOutsideModel : List Name :=
  [`Arlib.Computation]

/-- Constants defined neither under `Nfa/Model/` nor in an admitted
module, paired with the module defining them. -/
private def outsideModel (env : Environment) (cls : NameSet) : List (Name × Name) :=
  cls.toList.filterMap fun c =>
    let mod := moduleOf env c
    if (`Nfa.Model).isPrefixOf mod then none
    else if admittedOutsideModel.any (·.isPrefixOf mod) then none
    else some (c, mod)

/-- Names the elaborator generates for every declaration, which nobody wrote and
which therefore cannot be moved out of `Model/`. -/
private def autoGenerated : List String :=
  ["noConfusion", "noConfusionType", "casesOn", "recOn", "rec", "brecOn", "below",
   "ndrec", "injEq", "inj", "sizeOf_spec", "mk", "toCtorIdx", "ofNat", "eq_def",
   "elim", "ctorIdx", "ctorElim", "ctorElimType", "ofNat_ctorIdx", "eq_1", "repr",
   "default"]

private def isAutoGenerated (c : Name) : Bool :=
  -- `inst` can appear at any depth (`instReprFoo.repr.match_1`), and the
  -- elaborator numbers its match auxiliaries, so neither test can look only at
  -- the last component or only at a fixed list
  c.components.any (fun p => match p with
    | .str _ s => "inst".isPrefixOf s || "match_".isPrefixOf s
    | _ => false)
  || (match c.componentsRev.headD .anonymous with
      | .str _ s => autoGenerated.contains s
      | _ => false)

/-- Seeded from a definition's own body — use this on the algorithm. -/
elab "#modelClosure " id:ident : command => do
  let env ← getEnv
  let n ← liftCoreM <| Lean.realizeGlobalConstNoOverload id
  let cls := (closureAux env {} [n] {}).erase n
  match outsideModel env cls with
  | [] => logInfo m!"OK — closure of {n} is under Model/ or an admitted module ({cls.toList.length})"
  | bad => throwError m!"OUTSIDE Model/ in closure of {n}: {bad}"

/-- **A module holds exactly what its claims are about, and nothing else.**

`#surplusIn M from s₁ … sₙ` reports every author-written constant *defined* in a
module under `M` that the seeds do not reach. A seed that is a theorem
contributes its statement; a seed that is a definition contributes itself.

The closure checks say nothing in a statement escapes `Model/`. This says
nothing in a module escapes its own claims, and the pair together pin the
audited surface from both sides. Without it a module only ever grows: a
definition parked there for convenience is indistinguishable, to a reader, from
one the claims depend on, and the surface a human is asked to read silently
widens.

Run it twice, with different seeds: once on `Model/` from the headline
theorems, once on `Model/Program.lean` from the algorithm's own entry points.
The tighter seed is what keeps a definition the *statement* legitimately reaches
out of the *program*.

**Instances defined in the module are seeds too.** An instance is part of how
the module is written rather than something parked in it, and a currency's own
`Fintype` — whose witness list would otherwise report as surplus — is exactly
this. Nothing can hide there: an instance is a term of a class, so a definition
that is not one cannot be smuggled inside it.

Surplus is a **warning**, not a build error, because whether a surplus
definition should move or the claims should mention it is a judgment. What is
not a judgment is knowing which ones they are. -/
elab "#surplusIn " mod:ident " from " ids:ident+ : command => do
  let env ← getEnv
  let prefix_ := mod.getId
  let mut seeds : List Name := []
  let mut named : List Name := []
  for id in ids do
    let n ← liftCoreM <| Lean.realizeGlobalConstNoOverload id
    let some ci := env.find? n | throwError "unknown constant {n}"
    named := n :: named
    -- a theorem contributes its statement; a definition contributes itself
    let isP ← liftTermElabM (Lean.Meta.isProp ci.type)
    seeds := seeds ++ (if isP then ci.type.getUsedConstants.toList else [n])
  -- every instance the module declares is a seed: see the docstring
  for (c, _) in env.constants.toList do
    if c.isInternal then continue
    unless prefix_.isPrefixOf (moduleOf env c) do continue
    if ← liftTermElabM (Lean.Meta.isInstance c) then seeds := seeds ++ [c]
  -- a seed is reached by itself: a theorem does not appear in its own statement
  let mut keep := closureAux env {} seeds {}
  for n in named do keep := keep.insert n
  let mut surplus : Array Name := #[]
  for (c, _) in env.constants.toList do
    if c.isInternal || isAutoGenerated c then continue
    unless (`Nfa).isPrefixOf c do continue
    unless prefix_.isPrefixOf (moduleOf env c) do continue
    if keep.contains c then continue
    -- a field of a structure the claims reach is reached: the field is part of
    -- that structure, not a separate thing parked in the module
    if let some pi := env.getProjectionFnInfo? c then
      if keep.contains pi.ctorName.getPrefix then continue
    surplus := surplus.push c
  if surplus.isEmpty then
    logInfo m!"OK — every author-written constant under {prefix_} is reached by \
      its claims ({keep.toList.length} reached)."
  else
    logWarning m!"SURPLUS in {prefix_} — defined there, reached by none of its \
      claims, so it widens the audited surface without widening the claim: \
      {surplus.toList}"

/-- Seeded from a theorem's *type*, so the statement — not the proof — unfolds. -/
elab "#modelClosureOfType " id:ident : command => do
  let env ← getEnv
  let some ci := env.find? (← liftCoreM <| Lean.realizeGlobalConstNoOverload id)
    | throwError "unknown constant"
  let cls := closureAux env {} ci.type.getUsedConstants.toList {}
  match outsideModel env cls with
  | [] => logInfo m!"OK — the STATEMENT is under Model/ or an admitted module ({cls.toList.length})"
  | bad => throwError m!"OUTSIDE Model/ in the statement: {bad}"

/-- The operators a cost is read with.  `outProbR` is absent on purpose: it
is the accuracy operator.  The list is the one `seal.ts` already keeps. -/
private def resourceOperators : List Name :=
  [`Arlib.Computation.worstSpace, `Arlib.Computation.worstSteps,
   `Arlib.Computation.Charged.cost, `Arlib.Computation.Charged.space,
   `Arlib.Computation.Charged.steps, `Arlib.Computation.Charged.peakAt,
   `Arlib.Computation.Charged.netAt, `Arlib.Computation.Profile.net,
   `Arlib.Computation.Profile.peak, `Arlib.Computation.Profile.peakAt,
   `Arlib.Computation.Profile.netAt, `Arlib.Computation.Residency.at']

/-- Every `∀` and every `→` stripped, so what is left is the goal itself. -/
private partial def underBinders : Expr → Expr
  | .forallE _ _ b _ => underBinders b
  | .letE _ _ _ b _ => underBinders b
  | e => e

/-- The constants on each side of a top-level relation.

A bridge may relate the correctness object through a standard wrapper, for
example `(estimatorOutput P).map Prod.fst = Pseudocode.answerLaw P`.  The head
of the left side is then `PMF.map`, but the object that decides which theorem
can move is `estimatorOutput`. -/
private def relationConstants (e : Expr) : List Name :=
  let sides :=
    match e.getAppFnArgs with
    -- The layouts are not uniform, and `HEq` carries a type between its sides.
    | (`Eq, #[_, l, r]) => [l, r]
    | (`Iff, #[l, r]) => [l, r]
    | (`HEq, #[_, l, _, r]) => [l, r]
    | (`HasEquiv.Equiv, #[_, _, l, r]) => [l, r]
    -- `Equiv` (`≃`) is absent: its sides are types, so its head is a run
    -- carrier, and every claim about a run names that carrier.
    | _ => []
  sides.foldr (fun s acc =>
    let head := match s.getAppFn.constName? with | some n => [n] | none => []
    head ++ s.getUsedConstants.toList ++ acc) []

/-- **Which vocabulary a statement is written in.**

Reports; never refuses.  A statement's closure reaching `Model/Program` or
`Model/Run` is a claim about the charged program; one reaching `Interface/`
is about the pseudocode.  `Model/Prelude` and `Model/Prior` are neither —
the parameters and the assumption bundle are shared by both sides.

Asked of Lean rather than of the source because the two sides share names:
a development declares `run` in `Model/Program.lean` and again in
`Interface/Pseudocode.lean`, and a statement writes it bare. -/
elab "#statementSide " id:ident : command => do
  let env ← getEnv
  let n ← liftCoreM <| Lean.realizeGlobalConstNoOverload id
  let some ci := env.find? n | throwError "unknown constant"
  let seeds := ci.type.getUsedConstants.toList
  let cls := (closureAux env {} seeds {}).toList
  let mods := (cls.map (moduleOf env)).eraseDups
  let under (p : Name) : Bool := mods.any (p.isPrefixOf ·)
  let program := under `Nfa.Model.Program || under `Nfa.Model.Run
  let pseudocode := under `Nfa.Interface || under `Nfa.Model.Pseudocode
  -- From the seeds, not the closure: `closureAux` keeps only `Nfa`
  -- constants, and every operator here is arlib's.
  let cost := seeds.any (fun c => resourceOperators.contains c)
  -- The seeds again, and the same module test `program` uses. This answers
  -- *which* program objects, so a caller can ask what a statement is about.
  let isObject (c : Name) : Bool :=
    let md := moduleOf env c
    (`Nfa.Model.Program).isPrefixOf md || (`Nfa.Model.Run).isPrefixOf md
  let objects := seeds.eraseDups.filter isObject
  let relates := (relationConstants (underBinders ci.type)).eraseDups
  -- One line, and the lists joined by hand. `MessageData` breaks a list
  -- across lines, and the reader of this is a line-based scan.
  let reach := String.intercalate "," (mods.map toString)
  let objectsS := String.intercalate "," (objects.map toString)
  let relatesS := String.intercalate "," (relates.map toString)
  logInfo m!"STATEMENT-SIDE {n} program={program} pseudocode={pseudocode} \
cost={cost} reach={reach} objects={objectsS} relates={relatesS}"

end Nfa.Meta
