import CountingMatroid.Interface.Pseudocode
import Mathlib.Data.Set.Finite.List
import CountingMatroid.Analysis.AbortTapeBound
import CountingMatroid.Analysis.InaccurateNonzeroTapeBound

set_option autoImplicit false

namespace CountingMatroid.Analysis.SingleRunAccuracy

open CountingMatroid.Model

/-- INTERNAL: A block generated by the finite fair-bit source has exactly the
requested width, and every Boolean block of that width is possible.
TEXLINE: main.tex:1392-1421 -/
theorem fairTape_support_iff_length (m : ℕ) (bits : List Bool) :
    bits ∈ (CountingMatroid.Model.Run.fairTape m).support ↔ bits.length = m := by
  induction m generalizing bits with
  | zero =>
      change bits ∈ (PMF.pure ([] : List Bool)).support ↔ _
      rw [PMF.mem_support_pure_iff]
      simp
  | succ m ih =>
      change bits ∈ (PMF.bind CountingMatroid.Model.Run.fairBitLaw
        (fun b => PMF.bind (CountingMatroid.Model.Run.fairTape m)
          (fun rest => PMF.pure (b :: rest)))).support ↔ _
      rw [PMF.mem_support_bind_iff]
      constructor
      · rintro ⟨b, _, hb⟩
        rw [PMF.mem_support_bind_iff] at hb
        obtain ⟨rest, hrest, hcons⟩ := hb
        rw [PMF.mem_support_pure_iff] at hcons
        subst bits
        simpa using (ih rest).mp hrest
      · intro hlen
        cases bits with
        | nil => simp at hlen
        | cons b rest =>
            have hb : b ∈ CountingMatroid.Model.Run.fairBitLaw.support := by
              rw [PMF.mem_support_iff]
              simp [CountingMatroid.Model.Run.fairBitLaw, PMF.ofFintype_apply]
            refine ⟨b, hb, ?_⟩
            apply (PMF.mem_support_bind_iff _ _ _).mpr
            refine ⟨rest, (ih rest).mpr ?_, ?_⟩
            · simpa using hlen
            · exact (PMF.mem_support_pure_iff _ _).mpr rfl

/-- INTERNAL: The finite fair-bit source assigns the same mass to each block
of the requested length and zero mass to every other list.
TEXLINE: main.tex:1392-1421 -/
theorem fairTape_apply (m : ℕ) (bits : List Bool) :
    CountingMatroid.Model.Run.fairTape m bits =
      if bits.length = m then (1 / 2 : ENNReal) ^ m else 0 := by
  induction m generalizing bits with
  | zero =>
      change (PMF.pure ([] : List Bool)) bits = _
      cases bits <;> simp
  | succ m ih =>
      change (PMF.bind CountingMatroid.Model.Run.fairBitLaw
        (fun b => PMF.bind (CountingMatroid.Model.Run.fairTape m)
          (fun rest => PMF.pure (b :: rest)))) bits = _
      cases bits with
      | nil => simp [PMF.bind_apply, PMF.pure_apply]
      | cons b rest =>
          cases b <;> simp [PMF.bind_apply, PMF.pure_apply, ih,
            CountingMatroid.Model.Run.fairBitLaw, pow_succ] <;> simp [mul_comm]

/-- INTERNAL: The probability of a finite-tape event is its number of
length-`m` tapes times the mass of one tape.
TEXLINE: main.tex:1392-1421 -/
theorem fairTape_event_card (m : ℕ) (event : Set (List Bool)) :
    (CountingMatroid.Model.Run.fairTape m).toOuterMeasure event =
      (Set.ncard {bits : List Bool | bits.length = m ∧ bits ∈ event} : ENNReal) *
        (1 / 2 : ENNReal) ^ m := by
  classical
  let good : Set (List Bool) := {bits | bits.length = m ∧ bits ∈ event}
  have hfinite : good.Finite :=
    (List.finite_length_eq Bool m).subset (by intro bits h; exact h.1)
  have hevent :
      (CountingMatroid.Model.Run.fairTape m).toOuterMeasure event =
        (CountingMatroid.Model.Run.fairTape m).toOuterMeasure good := by
    apply PMF.toOuterMeasure_apply_eq_of_inter_support_eq
    ext bits
    simp only [Set.mem_inter_iff, fairTape_support_iff_length]
    change (bits ∈ event ∧ bits.length = m) ↔
      (bits.length = m ∧ bits ∈ event) ∧ bits.length = m
    tauto
  rw [hevent, ← hfinite.coe_toFinset, PMF.toOuterMeasure_apply_finset]
  simp only [fairTape_apply]
  have hlen : ∀ bits ∈ hfinite.toFinset, bits.length = m := by
    intro bits hbits
    exact (hfinite.mem_toFinset.mp hbits).1
  calc
    ∑ bits ∈ hfinite.toFinset,
        (if bits.length = m then (1 / 2 : ENNReal) ^ m else 0) =
        ∑ _bits ∈ hfinite.toFinset, (1 / 2 : ENNReal) ^ m := by
          apply Finset.sum_congr rfl
          intro bits hbits
          rw [if_pos (hlen bits hbits)]
    _ = _ := by simp [good, Set.ncard_eq_toFinset_card good hfinite]

/-- PAPER: main.tex:1253-1421
The capped annealing run, fed one fresh finite fair-bit block, misses the
relative-error interval with probability at most one quarter. -/
theorem single_run_accuracy_bound (n r : ℕ) (M₁ M₂ : Matroid (Fin n))
    (o₁ o₂ : IndependenceOracle n) (p : InputParams)
    (hfull : FullGround M₁ M₂) (hr : CommonRank r M₁ M₂)
    (h₁ : ExactOracle M₁ o₁) (h₂ : ExactOracle M₂ o₂)
    (hpositive : 0 < commonBaseCount M₁ M₂) :
    let s := CountingMatroid.Interface.Pseudocode.setup n p
    let runLaw :=
      (CountingMatroid.Model.Run.fairTape
        (CountingMatroid.Model.Run.blockLength n r p)).map
        (fun bits => CountingMatroid.Interface.Pseudocode.singleRun r o₁ o₂
          (fun i => (bits[i]?).getD false) s)
    runLaw.toOuterMeasure
      {y : ℚ | y < (1 - p.ε) * (commonBaseCount M₁ M₂ : ℚ) ∨
        (1 + p.ε) * (commonBaseCount M₁ M₂ : ℚ) < y} ≤
      (1 / 4 : ENNReal) := by
  dsimp only
  rw [PMF.toOuterMeasure_map_apply]
  rw [fairTape_event_card]
  let s := CountingMatroid.Interface.Pseudocode.setup n p
  let m := CountingMatroid.Model.Run.blockLength n r p
  let answer : List Bool → ℚ := fun bits =>
    CountingMatroid.Interface.Pseudocode.singleRun r o₁ o₂
      (fun i => (bits[i]?).getD false) s
  let aborts : Set (List Bool) := {bits | bits.length = m ∧ answer bits = 0}
  let inaccurate : Set (List Bool) := {bits | bits.length = m ∧
    answer bits ≠ 0 ∧
      (answer bits < (1 - p.ε) * (commonBaseCount M₁ M₂ : ℚ) ∨
       (1 + p.ε) * (commonBaseCount M₁ M₂ : ℚ) < answer bits)}
  have hsubset :
      {bits : List Bool | bits.length = m ∧
        bits ∈ (fun bits => answer bits) ⁻¹'
          {y : ℚ | y < (1 - p.ε) * (commonBaseCount M₁ M₂ : ℚ) ∨
            (1 + p.ε) * (commonBaseCount M₁ M₂ : ℚ) < y}} ⊆
        aborts ∪ inaccurate := by
    intro bits hbits
    by_cases hz : answer bits = 0
    · exact Or.inl ⟨hbits.1, hz⟩
    · exact Or.inr ⟨hbits.1, hz, hbits.2⟩
  have hfinite : (aborts ∪ inaccurate).Finite := by
    apply (List.finite_length_eq Bool m).subset
    intro bits hbits
    rcases hbits with h | h
    · exact h.1
    · exact h.1
  have habort := AbortTapeBound.abort_tape_mass_bound n r M₁ M₂ o₁ o₂ p
    hfull hr h₁ h₂ hpositive
  have hinaccurate :=
    InaccurateNonzeroTapeBound.inaccurate_nonzero_tape_mass_bound
      n r M₁ M₂ o₁ o₂ p hfull hr h₁ h₂ hpositive
  change (Set.ncard {bits : List Bool | bits.length = m ∧
    bits ∈ (fun bits => answer bits) ⁻¹'
      {y : ℚ | y < (1 - p.ε) * (commonBaseCount M₁ M₂ : ℚ) ∨
        (1 + p.ε) * (commonBaseCount M₁ M₂ : ℚ) < y}} : ENNReal) *
      (1 / 2 : ENNReal) ^ m ≤ 1 / 4
  calc
    _ ≤ (Set.ncard (aborts ∪ inaccurate) : ENNReal) * (1 / 2 : ENNReal) ^ m := by
      gcongr
    _ ≤ ((Set.ncard aborts : ENNReal) + Set.ncard inaccurate) *
          (1 / 2 : ENNReal) ^ m := by
      gcongr
      exact_mod_cast Set.ncard_union_le aborts inaccurate
    _ = (Set.ncard aborts : ENNReal) * (1 / 2 : ENNReal) ^ m +
          (Set.ncard inaccurate : ENNReal) * (1 / 2 : ENNReal) ^ m := by
      rw [add_mul]
    _ ≤ (1 / 8 : ENNReal) + 1 / 8 := add_le_add (by simpa [aborts, answer, s, m] using habort)
      (by simpa [inaccurate, answer, s, m] using hinaccurate)
    _ = 1 / 4 := by
      rw [show (1 / 8 : ENNReal) = (1 / 4 : ENNReal) / 2 by
        rw [show (8 : ENNReal) = 4 * 2 by norm_num]
        simp [div_eq_mul_inv, ENNReal.mul_inv]]
      exact ENNReal.add_halves _

end CountingMatroid.Analysis.SingleRunAccuracy

/-! ### Run record
Newest first. History, not instruction — what this file claims is above.

* r5 · open · split bad finite tapes into zero-output aborts and inaccurate nonzero outputs; the parent union proof checks, but both event-mass bounds remain open and the live child handoff was rejected mechanically.
* r4 · open · proved the exact finite-event cardinality formula; the bad-tape count still needs conditional phase estimates and capped-draw coupling.
* r3 · open · proved exact fair-tape point masses; the finite bad-block count still needs conditional phase estimates and capped-draw coupling.
* r2 · open · proved the fair-tape support/length characterization; the conditional phase estimates and capped-draw coupling are still absent.
* r1 · open · reduced the theorem to the fair-tape error event; `simp_all` and `aesop` leave the same probability bound, and the paper's phase estimates and finite-bit coupling are not formalized.
-/
